//Actions
const GET_PRODUCTS_STARTED = "GET_PRODUCTS_STARTED";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

const SAVE_PRODUCT = "SAVE_PRODUCT";
const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
const SAVE_PRODUCT_FAIL = "SAVE_PRODUCT_FAIL";

const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

const DELETE_PRODUCT = "DELETE_PRODUCT";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export {
  GET_PRODUCTS_STARTED,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILED,
  SAVE_PRODUCT,
  SAVE_PRODUCT_SUCCESS,
  SAVE_PRODUCT_FAIL,
  UPDATE_PRODUCT,
  UPDATE_PRODUCT_SUCCESS,
  UPDATE_PRODUCT_FAIL,
  DELETE_PRODUCT,
  DELETE_PRODUCT_SUCCESS,
  DELETE_PRODUCT_FAIL,
};
